export const browserCoreExamples = [
  "opencog browser status",
  "opencog browser start",
  "opencog browser stop",
  "opencog browser tabs",
  "opencog browser open https://example.com",
  "opencog browser focus abcd1234",
  "opencog browser close abcd1234",
  "opencog browser screenshot",
  "opencog browser screenshot --full-page",
  "opencog browser screenshot --ref 12",
  "opencog browser snapshot",
  "opencog browser snapshot --format aria --limit 200",
  "opencog browser snapshot --efficient",
  "opencog browser snapshot --labels",
];

export const browserActionExamples = [
  "opencog browser navigate https://example.com",
  "opencog browser resize 1280 720",
  "opencog browser click 12 --double",
  'opencog browser type 23 "hello" --submit',
  "opencog browser press Enter",
  "opencog browser hover 44",
  "opencog browser drag 10 11",
  "opencog browser select 9 OptionA OptionB",
  "opencog browser upload /tmp/file.pdf",
  'opencog browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opencog browser dialog --accept",
  'opencog browser wait --text "Done"',
  "opencog browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opencog browser console --level error",
  "opencog browser pdf",
];
